include:
  - template: Security/SAST.gitlab-ci.yml

image: node:18.14-alpine

stages:
  - build
  - test

cache:
  - key:
      files:
        - yarn.lock
    paths:
      - node_modules
      - .yarn

  # Cache NextJS files: https://nextjs.org/docs/messages/no-cache#gitlab-ci
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/cache/

build:
  stage: build
  script:
    - yarn -v
    - yarn install --cache-folder .yarn --frozen-lockfile
    - yarn run build

lint-code:
  stage: test
  script:
    - yarn run lint
    - yarn run check-format

unit-test:
  stage: test
  script:
    - 'yarn global add jest'
    - 'yarn add --dev jest-junit'
    - 'jest --ci --reporters=default --reporters=jest-junit'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml