stages:
  - build
  - test

# pnpm template: https://github.com/pnpm/pnpm/issues/1174#issuecomment-996719439
default:
  image: node:20.10-alpine
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      # Next.js: https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#gitlab-ci
      - .next/cache/
      - node_modules
      # pnpm: https://pnpm.io/continuous-integration#gitlab-ci
      - .pnpm-store
    policy: pull

build:
  stage: build
  script:
    - pnpm install
    - pnpm run build
  cache:
    <<: *global_cache
    policy: pull-push

lint:
  stage: test
  script:
    - pnpm run lint
    - pnpm run check-format

end-to-end-tests:
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  stage: test
  script:
    - pnpm run test