include:
  - template: Security/SAST.gitlab-ci.yml

image: node:16.14.0-alpine3.14

stages:
  - build
  - test

cache:
  - key:
      files:
        - yarn.lock
    paths:
      - node_modules/

  # Cache NextJS files: https://nextjs.org/docs/messages/no-cache#gitlab-ci
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/cache/

build-project:
  stage: build
  script:
    - yarn -v
    # Use instead of install for CI/CD: https://docs.npmjs.com/cli/v8/commands/npm-ci
    - yarn install --frozen-lockfile
    - yarn run build

lint-project:
  stage: test
  script:
    - yarn run lint
    - yarn run check-format

unit-test-job:
  stage: test
  script:
    - yarn test
